### ISSUE TITLE
When will commuter download project complete?

### ISSUE THREAD

**Issue by sohelajani** [zaidajani/ama#1]
As I was very excited about the commuter project, when will its download page be created? The sneak peek image was phenomenal, hope it turns into reality soon.

**Comment by zaidajani** [comment]
It Will be made soon, Request you to make a rough clone of it with react and have a pull request, and kindly have a look at the commuter download project at the project tab and keep a record of the todos.

**Comment by zaidajani** [comment]
Its made! Live at https://perfactors.com/commuter/
